server:
  port: 2001

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-tx-group  #nacos配置中心需要添加 service.vgroupMapping.${spring.application.name}-tx-group
  config:
    type: nacos
    nacos:
      namespace: "21ec2e7e-86d7-430e-9e31-33e3cee84728"
      username: nacos
      password: nacos
      group: SEATA_GROUP
      server-addr: localhost:8848
  registry:
    type: nacos
    nacos:
      namespace: "21ec2e7e-86d7-430e-9e31-33e3cee84728"
      username: nacos
      password: nacos
      group: SEATA_GROUP
      application: seata-server
      server-addr: localhost:8848
    
    
    
spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_order?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 




logging:
  level:
    io:
      seata: info
 
mybatis:
  mapperLocations: classpath:mapper/*.xml

  
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#  global-config:
#    db-config:
#      table-prefix: project_