server:
  port: 7001

  
eureka:
  instance:
    ip-address: 127.0.0.1
    hostname: eureka7001
  client:
    register-with-eureka: false #自己不注册自己
    fetch-registry: false #声明自己是注册中心不用在去检索服务
    service-url:
      defaultZone: http://eureka7002:7002/eureka/
  server:
    eviction-interval-timer-in-ms: 60000 #检查服务器时间间隔
    enable-self-preservation: true #保护机制
    
  
  
spring:
  application:
    name: euraka7001

    
