server:
  port: 9527
  
spring:
  application:
    name: cloud-payment-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #打开lb的动态路由负载均衡
      routes:
      - id: route1
#        uri: http://127.0.0.1:8001
        uri: lb://CLOUD-PAYMENT-SERVICE
        predicates:
          - Path=/get/**
      - id: route2
        uri: http://127.0.0.1:8001
        predicates:
          - Path=/timeout/**
      - id: route3
        uri: http://127.0.0.1:8001
        predicates:
          - Path=/**
          
    

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
  instance:
    instance-id: cloud-payment-gateway
    hostname: cloud-payment-gateway
    prefer-ip-address: true
    
