server:
  port: 8001
  
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/project?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 


mybatis:
  mapperLocations: classpath:mapper/*.xml

  
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      table-prefix: project_
      
      
eureka:
  instance:
    instance-id: eureka8001
    prefer-ip-address: true
    lease-renewal-interval-in-seconds:  1 #向服务端发送心跳时间
    lease-expiration-duration-in-seconds:  2 #2秒连比不上服务器就剔除这个客户端
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka, http://localhost:7002/eureka