server:
  port: 80
  
spring:
  application:
    name: cloud-consumer-service


eureka:
  instance: 
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/